name: Update News Final

on:
  schedule:
    - cron: '0 2 * * *'          # Nachts um 2 Uhr (Deep Clean & Pruning)
    - cron: '0 6-22/2 * * *'     # Alle 2 Stunden tagsüber
  workflow_dispatch:             # Manueller Start erlaubt

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Hier von 18 auf 20 ändern

    - name: Install Dependencies
      run: npm install rss-parser axios cheerio

    - name: Run Grabber
      run: node grabber.js

    - name: Create Config File
      run: |
        echo '{ "repository": "${{ github.repository }}" }' > config.json

    - name: Commit and Push all changes
      run: |
        git config --global user.name 'NewsBot'
        git config --global user.email 'bot@noreply.github.com'
        git add news.json config.json
        git commit -m "Update News, Briefing & FullText" || echo "Keine Änderungen"
        git push
